# Generated by Django 4.2.4 on 2023-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TextField(blank=True, null=True, verbose_name='Новое поле'),
        ),
    ]
